
package Rysowanie;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import Swiat.Organizm;
import Swiat.Swiat;

public class Mapa extends javax.swing.JPanel {

    private final static int WIELKOSC = 30;
    private Swiat swiat;
    /**
     * Creates new form Mapa
     */
    public Mapa() {
        initComponents();
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                super.mouseClicked(me);
                dodajOrganizm(me);
            }
        });
    }

    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs); //To change body of generated methods, choose Tools | Templates.
        Graphics2D g2d = (Graphics2D) grphcs;
        for(int i=0; i<swiat.getRozmiarY() * WIELKOSC; i+=WIELKOSC) {
            for(int j=0; j<swiat.getRozmiarX() * WIELKOSC; j+=WIELKOSC) {
                g2d.drawRect(j, i, WIELKOSC, WIELKOSC);
            }
        }
        for(int i=0; i<swiat.getIloscOrganizmow(); i++) {
            Organizm tmp = swiat.getOrganizm(i);
            g2d.setColor(tmp.getColor());
            g2d.fillRect(tmp.getPolozenieX()*WIELKOSC, tmp.getPolozenieY()*WIELKOSC, WIELKOSC, WIELKOSC);
        }
    }

    private void dodajOrganizm(MouseEvent me) {
        Object[] possibleValues = { "A", "L", "O", "W", "O", "b", "g", "m", "t", "j" };
        String selectedValue = (String)JOptionPane.showInputDialog(null, "Choose one", "Input", JOptionPane.INFORMATION_MESSAGE, null, possibleValues, possibleValues[0]);
        int organizm = swiat.znajdzPozycje(me.getX() / 30, + me.getY() / 30);
        if(organizm == -1) {
            if(selectedValue != null) {
                swiat.dodajOrganizm(me.getX() / 30, me.getY() / 30, selectedValue.charAt(0));
                repaint();
            }
        }
    }

    public Swiat getSwiat() {
        return swiat;
    }

    public void setSwiat(Swiat swiat) {
        this.swiat = swiat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
